### ISSUE TITLE
add proper email view(Embed the link) instead of whole link as a text.

### ISSUE THREAD

**Issue by het-patel99** [hvudeshi/SRIJAS#10]

**Comment by het-patel99** [comment]
I have updated this email function and now it works fine will all the details and the link is also embedded now. Below is the image which i received as the mail. 

![image](https://user-images.githubusercontent.com/44945317/141705268-de4e0852-5a2a-4c87-8768-2ca622dfd6dc.png)

**Comment by het-patel99** [comment]
Hardik and Vineet kindly check this and close the issue if its working fine for all.

**Comment by hvudeshi** [comment]
Yeah, it looks just like LinkedIn. Others' can also verify that and then it is good to go. @Vineet2311 @sal0ni @kalgeekotak99 you all can also share your thoughts for the same.

**Comment by Vineet2311** [comment]
We can add even more information along with that, what do you guys say ?

**Comment by sal0ni** [comment]
It can be done in the next phase.

**Comment by Vineet2311** [comment]
Ok, then everything looks fine, I will close it.
