### ISSUE TITLE
create and fill projectrubrics2 file

### ISSUE THREAD

**Issue by het-patel99** [hvudeshi/SRIJAS#12]

**Comment by het-patel99** [comment]
Kalgee, Hardik, Vineet, and Saloni kindly check our rubric file and do acknowledge if there's any thing left to add!!

**Comment by hvudeshi** [comment]
I am verifying it. I am changing a few of the stuff and we can add some docs files and give the path of that docs file as a URL.

**Comment by hvudeshi** [comment]
I have made the changes, @kalgeekotak99 @sal0ni you both check it once.

**Comment by sal0ni** [comment]
Perfect!

**Comment by kalgeekotak99** [comment]
Looks good.

**Comment by het-patel99** [comment]
@hvudeshi update the latest release in rubric file and provide link for that

**Comment by hvudeshi** [comment]
I have added the final release. v.8.0.0 and changed the link in the project rubrics file too. @het-patel99 check it once and close the issue.
