### ISSUE TITLE
add/update content  from readme.md

### ISSUE THREAD

**Issue by het-patel99** [hvudeshi/SRIJAS#14]

**Comment by Vineet2311** [comment]
I have updated the readme, please check it.

**Comment by sal0ni** [comment]
Yes but there are some updates to readme which I will add.

**Comment by hvudeshi** [comment]
I have added the DOI, and code coverage badge.

**Comment by het-patel99** [comment]
I have added our build: passing badge, and also have updated README.md file. @Vineet2311 you can close this issue now.
