### ISSUE TITLE
add UI to home.php

### ISSUE THREAD

**Issue by het-patel99** [hvudeshi/SRIJAS#19]

**Comment by hvudeshi** [comment]
I have added the UI to the home.php file. The page looks as follows:-
![ss-login](https://user-images.githubusercontent.com/22682878/141704804-36592b24-60ae-49bd-81f8-ef615d011fb7.png)

**Comment by het-patel99** [comment]
Hardik, this looks fine. Have you completed storing mail address and password into database?

**Comment by hvudeshi** [comment]
Yes, I have completed that and it looks good to me, if possible can anyone test this feature too?

**Comment by hvudeshi** [comment]
After the login page, I have added one more skill page too.
![ss-skills](https://user-images.githubusercontent.com/22682878/141720327-fd884f83-5ed5-4c9b-9bcc-d9ea1cfa17f1.png)


@Vineet2311 @het-patel99 @kalgeekotak99 @sal0ni share your thoughts on it?

**Comment by Vineet2311** [comment]
Yeah , I will test the feature. It looks fine

**Comment by sal0ni** [comment]
It looks nice.

**Comment by kalgeekotak99** [comment]
Looks good. But we can still improve UI.

**Comment by sal0ni** [comment]
We can keep this for the next phase.

**Comment by Vineet2311** [comment]
It is working fine on the Xampp server

**Comment by het-patel99** [comment]
@hvudeshi Test this on AWS!!

**Comment by hvudeshi** [comment]
I have already tested it and it is working fine. I am closing this issue.
