### ISSUE TITLE
Add indeed_scrapper.py

### ISSUE THREAD

**Issue by het-patel99** [hvudeshi/SRIJAS#21]

**Comment by sal0ni** [comment]
I've implemented scraper for indeed job portal: https://github.com/hvudeshi/SRIJAS/blob/main/Code/Scrapper/scrapper_indeed.py
Review it.

**Comment by Vineet2311** [comment]
Yes it is fine. Have you implemented the advanced filters ?

**Comment by kalgeekotak99** [comment]
I have added advanced filter.

**Comment by hvudeshi** [comment]
It is working fine on the AWS EC2 machine and data getting fetched from the RDS server.

**Comment by het-patel99** [comment]
Okay then great, now as this scrapper is working fine and we already have tested on AWS so @sal0ni you can close this issue.

**Comment by sal0ni** [comment]
Yes , I have reviewed it and I am closing this issue.
