### ISSUE TITLE
create new python file for sending email alerts.

### ISSUE THREAD

**Issue by het-patel99** [hvudeshi/SRIJAS#22]

**Comment by het-patel99** [comment]
The file has been updated, kindly check this in our github. File name is email_alert.py
(
![image](https://user-images.githubusercontent.com/44945317/141705546-a13d14f6-ed4e-4528-aacc-cc84dc9d1e7d.png)
)

**Comment by hvudeshi** [comment]
Have you checked the email alert in the local system?

**Comment by hvudeshi** [comment]
Can you also share how does it look in the email?

**Comment by het-patel99** [comment]
Yes i have checked in local its working fine.

**Comment by het-patel99** [comment]
I have attached a screenshot, kindly check that!!
(
![image](https://user-images.githubusercontent.com/44945317/141719539-2bdf5a3c-cd4c-4fcb-8ffc-68e45f9de42d.png)
)

**Comment by hvudeshi** [comment]
Yeah, it looks good. What u all think @Vineet2311 @sal0ni @kalgeekotak99?

**Comment by Vineet2311** [comment]
Yes

**Comment by sal0ni** [comment]
Yes

**Comment by Vineet2311** [comment]
Yes, you can add more information along with email alerts.

**Comment by sal0ni** [comment]
It can be done in the next phase.
