### ISSUE TITLE
Configuration update

### ISSUE THREAD

**Issue by hvudeshi** [hvudeshi/SRIJAS#34]
Bug in LinkedIn scrapper
File issue in Configuration Update Commit

**Comment by hvudeshi** [comment]
I have added two shell scripts in the SRIJAS/Code/Infrastructure/SRIJAS_AWS/ folder. This shell script is used in the SRIJAS/Code/Infrastructure/SRIJAS_AWS/ec2.tf file and this way instead of writing the shell script completely in the ec2.tf, I have called two different files and done configuration management respectively.

**Comment by het-patel99** [comment]
I just checked that, I guess the shell script created seems fine now. We will directly test later when we run whole project.  As of now we can close this issue.
