### ISSUE TITLE
Add new test case for indeed, linkedIn, and glassdoor

### ISSUE THREAD

**Issue by hvudeshi** [hvudeshi/SRIJAS#35]

**Comment by kalgeekotak99** [comment]
I have added test cases for scrapper_indeed, scrapper_glassdoor and scrapper_linkedIn.
File name: scrapper_indeed_test.py, scrapper_glassdoor_test.py and scrapper_linkedIn_test.py. 
{
 
![image](https://user-images.githubusercontent.com/43135408/141720185-9ba95df7-0123-4db5-8afa-2f9908caf7d6.png)
}

**Comment by Vineet2311** [comment]
Looks good

**Comment by sal0ni** [comment]
Seems good. Code coverage increased after adding these test cases.

**Comment by hvudeshi** [comment]
Test cases look good, @kalgeekotak99, you can close the issue.

**Comment by het-patel99** [comment]
I just verified these test cases, it looks great we can finally test this at last before submitting the project. You can close this issue for now.
