### ISSUE TITLE
Add new demo video.

### ISSUE THREAD

**Issue by hvudeshi** [hvudeshi/SRIJAS#37]

**Comment by Vineet2311** [comment]
I have made the video and added it. Please check it. 
Link : https://www.youtube.com/watch?v=2PqOaFu9pPU
@hvudeshi @sal0ni @het-patel99 @kalgeekotak99

**Comment by hvudeshi** [comment]
It looks good for me, as of now.

**Comment by het-patel99** [comment]
Yes, the demo is fine now. You can close this issue.
