### ISSUE TITLE
Add comments to the code

### ISSUE THREAD

**Issue by hvudeshi** [hvudeshi/SRIJAS#38]

**Comment by Vineet2311** [comment]
I have added the comment for the scrapper files, please check it.
<img width="1152" alt="Screenshot 2021-11-14 at 10 51 44 PM" src="https://user-images.githubusercontent.com/89501442/141719651-7a0864c1-3c64-441d-b163-dce1662a67a2.png">

**Comment by kalgeekotak99** [comment]
I have reviewed it. Looks good.

**Comment by sal0ni** [comment]
Yes. This looks fine.

**Comment by Vineet2311** [comment]
Yes

**Comment by hvudeshi** [comment]
@Vineet2311 you can close the issue.

**Comment by Vineet2311** [comment]
Yes , I am closing it.
