### ISSUE TITLE
Take threshold for matching job listing and resume from user

### ISSUE THREAD

**Issue by het-patel99** [hvudeshi/SRIJAS#6]

**Comment by hvudeshi** [comment]
I have added the threshold in the UI. The UI looks as follows:- 
![ss-index-page](https://user-images.githubusercontent.com/22682878/141704933-ec5bf919-3e5e-417d-9aa4-0b6772df7edc.png)

**Comment by het-patel99** [comment]
I have added the function for threshold. 
(
![image](https://user-images.githubusercontent.com/44945317/141705365-45e5456a-2bb4-4c7f-bc81-c7fd5268d97b.png
)

**Comment by het-patel99** [comment]
Saloni and Hardik could you please check this above image and see if there are any errors. I have tested this works for me.

**Comment by hvudeshi** [comment]
Yes, it is working fine in my local system. I am testing this on AWS.

**Comment by hvudeshi** [comment]
It is working on AWS too. I am closing the issue.
