### ISSUE TITLE
Take more advanced filters like date/duration , job location etc from the user and incorporate in scraper

### ISSUE THREAD

**Issue by het-patel99** [hvudeshi/SRIJAS#7]

**Comment by kalgeekotak99** [comment]
Added Filters for scrapper_indeed.py. Review it.
{
![image](https://user-images.githubusercontent.com/43135408/141720906-198db266-497c-4fe4-bda2-f8f19f3f1616.png)
}

**Comment by Vineet2311** [comment]
I have added for glass door and LinkedIn, please check it

**Comment by sal0ni** [comment]
Looks fine

**Comment by het-patel99** [comment]
@kalgeekotak99 Have you tested on local?

**Comment by kalgeekotak99** [comment]
Yes. It works fine.

**Comment by het-patel99** [comment]
Great!! You can close this issue now.
