### ISSUE TITLE
integrate the job portal with a basic login service

### ISSUE THREAD

**Issue by het-patel99** [hvudeshi/SRIJAS#8]

**Comment by hvudeshi** [comment]
I have added the login page and it looks as follows:- 
![ss-login](https://user-images.githubusercontent.com/22682878/141704960-da6e0cfd-67c7-4b41-a4ee-0a7975df6ace.png)


Also, added the session for the same. You all can verify the code, it's in the Web_App folder.

**Comment by het-patel99** [comment]
Okay cool!! Could you please also work on adding all these mail address and password into our database and also test if the user skills are fetched properly from the resume.

**Comment by hvudeshi** [comment]
It is already been added to the database and it is working fine for me on the  xampp server. I am testing it on AWS now.

**Comment by hvudeshi** [comment]
It is working on AWS too. I am closing the issue.
