### ISSUE TITLE
Structuring and syncing the scrapper code into one instead of two different files.

### ISSUE THREAD

**Issue by het-patel99** [hvudeshi/SRIJAS#9]

**Comment by het-patel99** [comment]
All the common functions are included in scrapper_main.py file. Additionally, 3 scrappers files are created scrapper_linkedIn, scrapper_glassdoor, and scrapper_indeed. 
(
![image](https://user-images.githubusercontent.com/44945317/141705684-9e5ccc2d-87f2-471d-a66c-c815d28fc005.png)
)

**Comment by het-patel99** [comment]
Hardik check for any errors or if there's any issue in this.

**Comment by hvudeshi** [comment]
Yeah, it looks good and it is working too.

**Comment by hvudeshi** [comment]
You can close the issue now.
